# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgre:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: '${PASSWORD_DB}'
    ports:
      - 5432:5432
